### ISSUE TITLE
Integration branch for Activities/RepoMan API

### ISSUE THREAD

**Issue by antis81** [macgitver/MacGitver#39]
@scunz Can you please rebase `sacu/activities` on `development` and create a PR out of `integrate/activities` by merging your branch there?

I assume you understand that, but just in case. I want to setup this branch relations:
`sacu/activities` :arrow_right: `integrate/activities` :arrow_right: `development`
`ngf/central-progress` :arrow_right: `integrate/activities` :arrow_right: `development`
... and further ...
`imaginary-third-developer/activities-related-thingy` :arrow_right: `integrate/activities` :arrow_right: `development`

**Comment by antis81** [comment]
Btw.: With this strategy I'm able to bring in the clone dialog changes as well.

**Comment by scunz** [comment]
@antis81 You won't even have anything to test against, if we were to take the activities branch away from repoman.

Sorry, this is a hard path to go, but I can't avoid it right now. While activities themselves might work on top of development, there's no point in having them if you cannot fill them (which ironically is the state of the code right now, too).

I'm not sure what exactly you mean with an integration branch here. There's two ways to work with branches for integration:
a) The merge every few minutes approach; suitable for non-git aware developers. You basically never change anything, develop in a branch, merge into the integration branch, then merge back again and also merge from integration branch whenever someone else merged something. This is stupid in git context.
b) The rebasing approach. This is i.e. how gerrit works (rebasing is just a super set of cherry-picking). You basically develop everything in your own branch and _never_ merge. You branch off of what you want to base your work upon and target that branch. If your target moves, you rebase. If you graduate, you do a fast-forward-merge.

**Comment by antis81** [comment]
> You won't even have anything to test against, if we were to take the activities branch away from repoman.

This is exactly the reason, why I'd prefer to talk via phone - I need to explain my situation and the text would become huge. In addition I simply like to try out QTox (it's a 5-10 minutes task), which doesn't require a server and thus is pretty much similar to exchanging phone numbers (just, that the phone number is 2 miles long :smile:). So, whenever you can get a time slot, please let's try it (just for fun).

In shortest text I can write:
I moved my `Private` branch from `development` to `sacu/activities` - very, very bad decision. It compiles and includes the changes I need to move / redesign / rewrite `ngf/central-progress` (the activity progress UI part). The downside is: There's basically no way, to move `Private` back to `development` before the whole - pretty long running - topic is done.

So my situation is:
My `Private` branch sits on top of `development` - excluding `sacu/activities`.

Let me put the idea with the "integration" branch aside and tell you what I need:
I need your changes from `sacu/activities` in the first place, which builds the base platform for `ngf/central-progress`. As I need your branch in my `Private` branch, I have two options - either merge or copy (cherry-pick) `sacu/activities` on top of my private branch. I'll have to do this, every single time you rebase.

In the current branch setup `ngf/central-progress` is rebased on `sacu/activities`. Your latest big extractions now force me to rebase again and re-resolve the conflicts on my side ... Which leads me to the (correct) decision to cut off and separate `ngf/central-progress` again (making it uncompilable as it will contain the :file_folder: `libActivities` folder - with separate files in it).

Now let's come back to the "integration" branch idea. If we merge our changes here (just like we would merge the - still uncompilable feature branches - to development), we create a central place, where our feature branches will be merged together. This branch breaks features, but is compilable and testable. Actually we never need to merge this "integration" branch. Instead, when everything is done, we can merge all the single feature branches in one go into development and they will work. Then we can delete the "integration" branch and it will look like we are the heroes fo the century :smile:.

Do you have a better advice?

EDIT: Sorry, the text became huge :innocent: :smile:?

**Comment by scunz** [comment]
The point is that this merge **will not work** once repoman or activities are rebased. Fix your workflow instead; see my mail. I'm not finished actually, but I'll hit the send button right now :)

**Comment by antis81** [comment]
The missing part on my side is the script. I'll have a look at that later as I need to get some other stuff done.
