### ISSUE TITLE
Another CMake warning

### ISSUE THREAD

**Issue by antis81** [macgitver/MacGitver#41]
The following warning bothers me for some time now:

``` bash
CMake Warning (dev) at /usr/local/lib/cmake/RAD-Tools/RAD-Tools/Qt5.cmake:116 (configure_file):
  configure_file called with unknown argument(s):

   COPY_ONLY
```

@scunz Can you please write a sentence about what this is meant for and if it is intended to stay in RAD-Tools?

**Comment by scunz** [comment]
It's just a customised version of the [default](https://github.com/qtproject/qtbase/blob/affba56094d972bb28a122c17e6a43373be5d1dd/src/corelib/Qt5CoreMacros.cmake#L190-L239)

**Comment by antis81** [comment]
Does it mean I can remove that attribute in MGV?

**Comment by scunz** [comment]
Remove the underscore and push that to RAD-Tools.

**Comment by antis81** [comment]
Should be done, thanks.
