### ISSUE TITLE
Repo Open Dialog

### ISSUE THREAD

**Issue by scunz** [macgitver/MacGitver#7]
@antis81, we currently have the clone and the create repository dialogs in Mod-Repository. Only the dialog code for opening a repository lives in the core.

It actually feels wrong there. Can i move it away from there and put it in to mod-repo, too?

**Comment by antis81** [comment]
Uhm, seems good. I don't see any reason against that. This one's still from the very beginning.

**Comment by scunz** [comment]
Okay. Gonna do it in two steps:
1. Send a PR to add it to MacGitverModules, merge this and rebase my refactoring upon that.
2. Remove it in the core during the "refactor branch work"
